---
abstract: 'apply database migrations via scripts in a directory'
author:
  - 'Jonathan Taylor <jon@local>'
build_requires: {}
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.66, CPAN::Meta::Converter version 2.132830'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: DB-SQL-Migrations
no_index:
  directory:
    - t
    - inc
resources:
  repository: git://github.com/jontaylor/DB-SQL-Migrations.git
version: 0.07
